server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8089
  servlet:
    context-path: /

spring:
  datasource:
    dynamic:
      primary: master
      druid:
        initial-size: 16
        max-active: 80
        min-idle: 16
        max-wait: 30000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://188.107.240.98:3306/safety?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useSSL=false
          username: root
          password: OoZh1234!@#$
  data:
    jdbc:
      dialect: mysql

  kafka:
    bootstrap-servers: 10.209.44.87:9092,10.209.44.103:9092,10.209.44.114:9092
    consumer:
      max-poll-interval-ms: 1800000
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: alarm-consumer-prod-v1
      max-poll-records: 10000
      fetch-min-size: 1
      fetch-max-wait: 10000
    listener:
      concurrency: 8
      missing-topics-fatal: false
      ack-mode: MANUAL
      type: batch


  #Redis???
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 20
      # 配置队列大小
      queue_capacity: 999
      name:
        prefix: async-service-
